#401 Returning to previous page instead of sign in page
hivesolutions/appier_extras pull request #40
Opened 2022-07-05 10:57 UTC by 3rdvision

| - | - |
| --- | --- |
| Issue | https://github.com/ripe-tech/ripe-robin-revamp/issues/401 - This is also reproducible for any oauth login flow -- instead of returning to sign in page we should return to the previous page that has all the parameters like `?next=...` necessary to not lose the login flow. |
| Decisions | - Recover password with link to return to the previous page instead of the sign in page |

2022-07-05 10:57 UTC, 3rdvision commented
@joamag manual assign

2022-07-06 08:55 UTC, joamag commented
This is not the best fix, let's instead propagate the `next` value to the recover password page instead and then use it in the login link :)

2022-07-06 11:08 UTC, 3rdvision commented
@joamag Done!

2022-07-30 10:29 UTC, joamag commented
@3rdvision schedule 15 min to go over this one https://calendly.com/joao-platforme/code-review

2022-08-01 14:39 UTC, joamag requested changes

2022-08-01 14:39 UTC, joamag commented on src/appier_extras/parts/admin/templates/fluid/recover.html.tpl
> -                <a href="{{ url_for('admin.login') }}">return to sign in</a>
```html
<a href="{{ url_for('admin.login', next = next) }}">return to sign in</a>
```

2022-08-01 14:39 UTC, joamag commented on src/appier_extras/parts/admin/templates/fluid/signin.html.tpl
> -                <a href="{{ url_for('admin.recover') }}">Forgot your password?</a>
```html
<a href="{{ url_for('admin.recover', next = next) }}">Forgot your password?</a>
```

2022-08-01 15:33 UTC, 3rdvision commented
@joamag Simplifying to `url_for('admin.recover', next = next)` works but when `&next=` it adds 1 empty URL parameter when next is empty string.
![image](https://user-images.githubusercontent.com/24736423/182185719-ef52a924-be57-4e3e-8229-cf17a1397393.png)

2022-08-01 15:55 UTC, 3rdvision commented
@joamag I simplified by setting next to `None` in case it comes as empty string. This way `url_for` works as expected :smile:

2022-08-02 10:32 UTC, joamag requested changes

2022-08-02 10:32 UTC, joamag commented on src/appier_extras/parts/admin/templates/fluid/signin.html.tpl
> +                <a href="{{ url_for('admin.login', next=next) }}">Forgot your password?</a>
space in next

2022-08-02 10:32 UTC, joamag commented on src/appier_extras/parts/admin/templates/fluid/signin.html.tpl
> +{% set next = request.args.get("next")[0] if request.args.get("next")[0] else None %}
avoid request args and use the route to obtain the next value

2022-08-02 10:32 UTC, joamag commented on src/appier_extras/parts/admin/templates/fluid/recover.html.tpl
> +                <a href="{{ url_for("admin.login", next = next) }}">return to sign in</a>
use ' to avoid escaping issue (keep in mind you're inside ")

2022-08-02 10:33 UTC, joamag commented
@3rdvision I'm going to merge the PR and run the changes myself to speed up the process, I'll share the commit afterward

2022-08-02 10:33 UTC, merged

2022-08-02 10:43 UTC, joamag commented
@3rdvision here it is ;) https://github.com/hivesolutions/appier_extras/commit/0be8c3c628ffa2e2197c34e666ff0c245e955784